name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: job_radar
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up uv package manager
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run pre-commit hooks (linters & formatters)
        uses: pre-commit/action@v3.0.1

      - name: Run test suite with isolated database
        env:
          DATABASE_URL: postgresql://postgres:secret_password@localhost:5432/job_radar
        run: uv run pytest

      - name: Build Docker image for deployment validation
        run: docker build -t job-radar-backend .
